// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqE-AAM4TFcWg37s_gLSlcxdqm8NaFtW0',
    appId: '1:108669530022:web:041dabe0b8e91adac36967',
    messagingSenderId: '108669530022',
    projectId: 'diary-app-d8606',
    authDomain: 'diary-app-d8606.firebaseapp.com',
    databaseURL: 'https://diary-app-d8606-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'diary-app-d8606.firebasestorage.app',
    measurementId: 'G-SQFWF93G4F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3mgjtG7cMhID1B45PbwP3szX98TbFrZc',
    appId: '1:108669530022:android:f67b8d6c3ce8fcd4c36967',
    messagingSenderId: '108669530022',
    projectId: 'diary-app-d8606',
    databaseURL: 'https://diary-app-d8606-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'diary-app-d8606.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC52A5D3Vl2TuBp1bJYblWjAesq0gULFOA',
    appId: '1:108669530022:ios:eabadff4eee8f09dc36967',
    messagingSenderId: '108669530022',
    projectId: 'diary-app-d8606',
    databaseURL: 'https://diary-app-d8606-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'diary-app-d8606.firebasestorage.app',
    iosBundleId: 'com.example.diaryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC52A5D3Vl2TuBp1bJYblWjAesq0gULFOA',
    appId: '1:108669530022:ios:eabadff4eee8f09dc36967',
    messagingSenderId: '108669530022',
    projectId: 'diary-app-d8606',
    databaseURL: 'https://diary-app-d8606-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'diary-app-d8606.firebasestorage.app',
    iosBundleId: 'com.example.diaryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqE-AAM4TFcWg37s_gLSlcxdqm8NaFtW0',
    appId: '1:108669530022:web:69b1e6169bae6015c36967',
    messagingSenderId: '108669530022',
    projectId: 'diary-app-d8606',
    authDomain: 'diary-app-d8606.firebaseapp.com',
    databaseURL: 'https://diary-app-d8606-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'diary-app-d8606.firebasestorage.app',
    measurementId: 'G-XM9E4LFBCY',
  );
}
